/* check_parity.js - verify web/ventsim.js against the Python reference cases.
 *
 *   node tools/check_parity.js
 *
 * Reads web/cases.json (produced by tools/gen_cases.py) and replays every case
 * with the JavaScript port.  Exits 1 if any field exceeds its tolerance.
 *
 * Steady cases.
 *   Most of them were generated by a direct `solve_steady(patient, vent, hco3)`
 *   call, which is the primary interpretation.  The twelve cases whose id is a
 *   scenario key were instead generated from `Scenario.build()`: a Simulation at
 *   the scenario settings, let its kidneys adapt for `adapt_hours`, equilibrate,
 *   and sampled with `sim.current()` - which pins drive/gases as model state.
 *   Both interpretations are evaluated for those twelve and the closer one is
 *   reported; only `chronic_hypercapnic` actually needs the build path (its
 *   bicarbonate comes from a 48 h renal adaptation).
 *
 * Dynamic cases.
 *   A fresh Simulation, then per step entry: apply `changes` to the ventilator,
 *   advance exactly round(span/dt) steps of size dt (span = gap to the previous
 *   entry) and compare.  The `start` block of a dynamic case is written by
 *   gen_cases.py *after* the step loop, i.e. it is the state at the end of the
 *   whole sequence, so it is compared there (verified: it equals the last step's
 *   expect to the last bit).
 */
'use strict';

var fs = require('fs');
var path = require('path');
var V = require('../web/ventsim.js');

var ROOT = path.resolve(__dirname, '..');
var CASES = JSON.parse(fs.readFileSync(path.join(ROOT, 'web', 'cases.json'), 'utf8'));

/* ---------------------------------------------------------------- tolerances
 * |delta| <= abs  OR  |delta| <= rel * |reference|   (whichever is generous)
 */
var TOL_DEFAULT = { abs: 0.02, rel: 2e-5 };
var TOL_O2 = { abs: 0.05, rel: 2e-5 };
var TOL_DYNAMIC = { abs: 0.05, rel: 0.005 };
var TOL_FIELDS = {
  pao2: TOL_O2,
  cao2: TOL_O2,
  cvao2_diff: TOL_O2,
  do2: TOL_O2
};
/* Scenario builds in scenarios.py: key -> adapt_hours. */
var SCENARIO_BUILDS = {
  normal: 0.0, ards_mild: 0.0, ards_mod: 0.0, ards_severe: 0.0,
  pneumonia: 0.0, copd: 0.0, asthma: 0.0, pe: 0.0, fibrosis: 0.0,
  obesity: 0.0, chronic_hypercapnic: 48.0, weaning: 0.0
};

function tolFor(field, dynamic) {
  if (dynamic) return TOL_DYNAMIC;
  return TOL_FIELDS[field] || TOL_DEFAULT;
}
function withinTol(delta, ref, tol) {
  if (delta <= tol.abs) return true;
  if (ref !== 0 && delta <= tol.rel * Math.abs(ref)) return true;
  return false;
}

function pyRound(x) {
  var f = Math.floor(x), d = x - f, r;
  if (d > 0.5) r = f + 1;
  else if (d < 0.5) r = f;
  else r = (f % 2 === 0) ? f : f + 1;
  return r;
}

/* ---------------------------------------------------------------- comparing */
function diffResult(res, expect, dynamic) {
  var worst = null;                       /* absolute */
  var worstRel = null;                    /* relative  */
  var fails = [];
  var deltas = [];                        /* every field, for the summary */
  var keys = Object.keys(expect);
  for (var i = 0; i < keys.length; i++) {
    var k = keys[i], ref = expect[k], got = res[k];
    if (typeof got !== 'number' || !isFinite(got)) {
      fails.push(k + ': js=' + got + ' ref=' + ref + ' (not a number)');
      continue;
    }
    var ad = Math.abs(got - ref);
    var rel = ref !== 0 ? ad / Math.abs(ref) : 0;
    deltas.push({ k: k, ad: ad, rel: rel, got: got, ref: ref });
    if (worst === null || ad > worst.ad) worst = { ad: ad, k: k, got: got, ref: ref };
    if (ref !== 0 && (worstRel === null || rel > worstRel.rel)) {
      worstRel = { ad: ad, rel: rel, k: k, got: got, ref: ref };
    }
    var tol = tolFor(k, dynamic);
    if (!withinTol(ad, ref, tol)) {
      fails.push(k + ': js=' + got + ' ref=' + ref + ' d=' + ad +
        ' (tol abs ' + tol.abs + ', rel ' + tol.rel + ')');
    }
  }
  return { worst: worst, worstRel: worstRel, fails: fails, deltas: deltas };
}

/* --------------------------------------------------------------- case setup */
function patientOf(c) { return new V.Patient(c.patient); }
function ventOf(c) { return new V.Vent(c.vent); }

function runSteadyDirect(c) {
  var opts = {};
  if (c.hco3 !== null && c.hco3 !== undefined) opts.hco3 = c.hco3;
  return V.solveSteady(patientOf(c), ventOf(c), opts);
}
/* Scenario.build(): Simulation at scenario settings, adapt, equilibrate. */
function runScenarioBuild(c, adaptHours) {
  var sim = new V.Simulation(patientOf(c), ventOf(c));
  if (adaptHours > 0) sim.adapt(adaptHours);
  if (adaptHours > 0) sim.equilibrate();
  return sim;
}

function runDynamic(c) {
  var dt = c.dt;
  var sim = new V.Simulation(patientOf(c), ventOf(c));
  var out = [];
  var tPrev = 0.0;
  for (var i = 0; i < c.steps.length; i++) {
    var st = c.steps[i];
    if (st.changes && Object.keys(st.changes).length > 0) sim.setVent(st.changes);
    var span = st.t_min - tPrev;
    var nSteps = 0;
    if (span > 0) {
      nSteps = Math.max(pyRound(span / dt), 1);
      for (var k = 0; k < nSteps; k++) sim.step(dt);
    }
    tPrev = st.t_min;
    out.push({ t_min: st.t_min, nSteps: nSteps, res: sim.current() });
  }
  return { sim: sim, out: out };
}

/* ------------------------------------------------------------------ main */
console.log('cases.json version ' + CASES.version + ', ' + CASES.n_cases + ' cases' +
  ' (' + CASES.cases.length + ' read)');

var worstPerField = {};      /* field -> {ad, got, ref, id}, path that was used */
var altPerField = {};        /* alternative reading of a steady case that did not apply */
var nFail = 0;
var nCases = 0;
var failIds = [];

function noteWorst(id, d, map) {
  if (!d || !d.deltas) return;
  for (var i = 0; i < d.deltas.length; i++) {
    var w = d.deltas[i];
    var cur = map[w.k];
    if (!cur || w.ad > cur.ad) {
      map[w.k] = { ad: w.ad, got: w.got, ref: w.ref, id: id };
    }
  }
}

for (var ci = 0; ci < CASES.cases.length; ci++) {
  var c = CASES.cases[ci];
  nCases++;
  if (c.kind === 'steady') {
    /* The authoritative interpretation is the direct call the case was built from. */
    var dDirect = diffResult(runSteadyDirect(c), c.expect, false);
    var mode = 'solve_steady';
    var hco3Err = null;
    var best = dDirect;
    var usedAlt = false;
    if (dDirect.fails.length &&
        Object.prototype.hasOwnProperty.call(SCENARIO_BUILDS, c.id)) {
      /* gen_cases built the scenario cases from Scenario.build() + sim.current():
         the drive and the gases are model state there, not freshly solved, and
         the chronic case carries 48 h of renal adaptation in its bicarbonate. */
      var adapt = SCENARIO_BUILDS[c.id];
      var simB = runScenarioBuild(c, adapt);
      hco3Err = Math.abs(simB.hco3 - c.hco3);
      var dBuild = diffResult(simB.current(), c.expect, false);
      if (!dBuild.fails.length || (dBuild.worst && dDirect.worst &&
                                   dBuild.worst.ad < dDirect.worst.ad)) {
        best = dBuild;
        mode = 'Scenario.build(h=' + adapt + ') + sim.current()';
        usedAlt = true;
      }
      noteWorst(c.id + (usedAlt ? '/direct' : ''), dDirect,
        usedAlt ? altPerField : worstPerField);
      noteWorst(c.id, dBuild, usedAlt ? worstPerField : altPerField);
    } else {
      noteWorst(c.id, dDirect, worstPerField);
    }
    var bad = best.fails.length > 0;
    if (bad) { nFail++; failIds.push(c.id); }
    console.log((bad ? 'FAIL ' : 'ok   ') + pad(c.id, 26) + ' steady ' + pad(mode, 34) +
      ' worst abs ' + fmt(best.worst.ad) + ' [' + best.worst.k + ']' +
      '  worst rel ' + (best.worstRel ? fmt(best.worstRel.rel, 10) : '-') +
      ' [' + (best.worstRel ? best.worstRel.k : '-') + ']' +
      (hco3Err !== null ? '  hco3 d=' + fmt(hco3Err, 10) : ''));
    if (bad) {
      for (var fi = 0; fi < best.fails.length; fi++) console.log('        ' + best.fails[fi]);
    }
  } else {
    var fresh = new V.Simulation(patientOf(c), ventOf(c));
    var dFresh = diffResult(fresh.current(), c.start, true);
    var run = runDynamic(c);
    var ok = true;
    /* start = state after the whole sequence (gen_cases writes it there) */
    var dStart = diffResult(run.sim.current(), c.start, true);
    noteWorst(c.id + '@start', dStart, worstPerField);
    if (dStart.fails.length) { ok = false; }
    var msgs = [];
    var worstStep = null;
    for (var si = 0; si < run.out.length; si++) {
      var o = run.out[si];
      var d = diffResult(o.res, c.steps[si].expect, true);
      noteWorst(c.id + '@' + o.t_min, d, worstPerField);
      if (!worstStep || d.worst.ad > worstStep.d.worst.ad) worstStep = { d: d, t: o.t_min, n: o.nSteps };
      if (d.fails.length) {
        ok = false;
        for (var fj = 0; fj < d.fails.length; fj++) msgs.push('        t=' + o.t_min + ' ' + d.fails[fj]);
      }
    }
    if (!ok) { nFail++; failIds.push(c.id); }
    console.log((ok ? 'ok   ' : 'FAIL ') + pad(c.id, 26) + ' dynamic dt=' + c.dt +
      ' steps=' + run.out.map(function (x) { return x.nSteps; }).join('+') +
      '  worst abs ' + fmt(worstStep.d.worst.ad) + ' [' + worstStep.d.worst.k + ' @t=' + worstStep.t + ']' +
      '  worst rel ' + fmt(worstStep.d.worstRel ? worstStep.d.worstRel.rel : 0, 10) +
      '  start worst abs ' + fmt(dStart.worst.ad) + ' [' + dStart.worst.k + ']' +
      '  (t=0 vs start: ' + fmt(dFresh.worst.ad, 4) + ')');
    for (var mi = 0; mi < msgs.length; mi++) console.log(msgs[mi]);
  }
}

function pad(s, w) { s = String(s); while (s.length < w) s += ' '; return s; }
function fmt(x, dg) {
  if (x === null || x === undefined) return '-';
  if (dg === undefined) dg = 8;
  if (Math.abs(x) >= 1e-4 && Math.abs(x) < 1e6) return x.toFixed(dg > 6 ? 6 : dg);
  return x.toExponential(dg > 4 ? 4 : dg);
}

/* ------------------------------------------------------------------ summary */
console.log('');
console.log('=== worst deviation per field over all comparisons ===');
var fields = Object.keys(worstPerField).sort(function (a, b) {
  return worstPerField[b].ad - worstPerField[a].ad;
});
for (var fI = 0; fI < fields.length; fI++) {
  var f = fields[fI], e = worstPerField[f], tol = TOL_FIELDS[f] || TOL_DEFAULT;
  console.log(pad(f, 14) + ' worst abs ' + fmt(e.ad, 10) +
    '   ref ' + fmt(e.ref, 8) + '  js ' + fmt(e.got, 8) +
    '   in ' + e.id + '   tol abs ' + tol.abs + ' / rel ' + tol.rel);
}
console.log('');
console.log('cases checked: ' + nCases + '   failing: ' + nFail);
if (nFail) {
  console.log('FAILED: ' + failIds.join(', '));
  process.exit(1);
}
console.log('PARITY OK: every field within tolerance');

var altFields = Object.keys(altPerField).sort(function (a, b) {
  return altPerField[b].ad - altPerField[a].ad;
});
if (altFields.length) {
  console.log('');
  console.log('alternative reading (not the path gen_cases used for those cases):');
  for (var ai = 0; ai < altFields.length && ai < 6; ai++) {
    var af = altFields[ai], ae = altPerField[af];
    console.log('    ' + pad(af, 12) + ' worst abs ' + fmt(ae.ad, 6) + ' in ' + ae.id);
  }
}
